# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ppoi_field',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/home/andrey/PycharmProjects/testbt/media/user_photos/'),
        ),
    ]
