# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170308_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='/media/user_photos/default.jpg', upload_to='/home/andrey/PycharmProjects/testbt/media/user_photos/'),
        ),
    ]
