# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170308_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Salary'),
        ),
    ]
