# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 21:31
from __future__ import unicode_literals

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170308_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocs',
            name='doc',
            field=models.FileField(upload_to=core.models.upload_file_name),
        ),
    ]
